/**
 * Per-locale UI chrome (nav, form, share). Page body copy lives in _includes/content/<lang>/.
 * When English UI chrome changes, update the matching keys here for every language.
 */
module.exports = {
  en: {
    brandTitle: 'Faith, Compared',
    brandHtml: 'Faith<span>,</span> Compared',
    nav: {
      home: 'Home',
      religions: 'All Religions',
      compare: 'Compare Lab',
      islam: 'Christianity ↔ Islam',
      evidence: 'Evidence',
      questions: 'Questions',
      objections: 'Objections',
      restoration: 'Which Christianity?',
      atheism: 'Atheism',
      sources: 'Sources',
      contact: 'Contact',
      philosophy: 'What Matters →',
      happiness: 'Happiness →',
      stats: 'Visitor map',
      menu: 'Menu',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
    },
    essayNav: {
      philosophy: [
        { href: '#big-questions', label: 'The Questions' },
        { href: '#convergence', label: 'Convergence' },
        { href: '#philosophers', label: 'Philosophers' },
        { href: '#research', label: 'The Research' },
        { href: '#synthesis', label: 'Synthesis' },
        { href: '#tensions', label: 'Tensions' },
        { href: '#conclusion', label: 'Conclusion' },
        { href: '#sources', label: 'Sources' },
      ],
      happiness: [
        { href: '#question', label: 'The Question' },
        { href: '#research', label: 'Research' },
        { href: '#traditions', label: 'Traditions' },
        { href: '#practice', label: 'Practice' },
        { href: '#sources', label: 'Sources' },
      ],
      stats: [
        { href: 'index.html#/religions', label: 'All Religions' },
        { href: 'index.html#/compare', label: 'Compare Lab' },
        { href: 'philosophy.html', label: 'What Matters' },
        { href: 'index.html#/contact', label: 'Contact' },
      ],
    },
    footer:
      'Faith, Compared · Built from evangelical apologetics sources · For study and discussion — always verify with the original texts.',
    backToJourney: '← Back to the journey',
    backHome: '← Home',
    i18n: {
      sending: 'Sending…',
      thanks: 'Thank you — your comment is on its way.',
      error: 'Something went wrong — please try again in a moment.',
      send: 'Send comment →',
      subject: 'New comment on comparereligion.com',
      continueChapter: '▶ Continue where you left off — Chapter {n} →',
      share: {
        site: {
          title: 'Faith, Compared',
          text: 'Seventeen worldviews. One honest comparison. Explore what the world’s religions actually teach:',
          url: 'https://comparereligion.com/',
        },
        compare: {
          title: 'Faith, Compared — Comparison Lab',
          text: 'Set any of the world’s religions side by side and compare what they actually teach:',
          url: 'https://comparereligion.com/#/compare',
        },
      },
    },
  },
  es: {
    brandTitle: 'Fe, Comparada',
    brandHtml: 'Fe<span>,</span> Comparada',
    nav: {
      home: 'Inicio',
      religions: 'Religiones',
      compare: 'Comparar',
      islam: 'Cristianismo ↔ Islam',
      evidence: 'Evidencia',
      questions: 'Preguntas',
      objections: 'Objeciones',
      restoration: '¿Cuál cristianismo?',
      atheism: 'Ateísmo',
      sources: 'Fuentes',
      contact: 'Contacto',
      philosophy: 'Lo que importa →',
      happiness: 'Felicidad →',
      stats: 'Mapa de visitantes',
      menu: 'Menú',
      openMenu: 'Abrir menú',
      closeMenu: 'Cerrar menú',
    },
    essayNav: {
      philosophy: [
        { href: '#big-questions', label: 'Las preguntas' },
        { href: '#convergence', label: 'Convergencia' },
        { href: '#philosophers', label: 'Filósofos' },
        { href: '#research', label: 'La investigación' },
        { href: '#synthesis', label: 'Síntesis' },
        { href: '#tensions', label: 'Tensiones' },
        { href: '#conclusion', label: 'Conclusión' },
        { href: '#sources', label: 'Fuentes' },
      ],
      happiness: [
        { href: '#question', label: 'La pregunta' },
        { href: '#research', label: 'Investigación' },
        { href: '#traditions', label: 'Tradiciones' },
        { href: '#practice', label: 'Práctica' },
        { href: '#sources', label: 'Fuentes' },
      ],
      stats: [
        { href: 'index.html#/religions', label: 'Religiones' },
        { href: 'index.html#/compare', label: 'Comparar' },
        { href: 'philosophy.html', label: 'Lo que importa' },
        { href: 'index.html#/contact', label: 'Contacto' },
      ],
    },
    footer:
      'Fe, Comparada · Construido con fuentes de apologética evangélica · Para estudio y conversación — verifica siempre con los textos originales.',
    backToJourney: '← Volver al recorrido',
    backHome: '← Inicio',
    i18n: {
      sending: 'Enviando…',
      thanks: 'Gracias — tu comentario está en camino.',
      error: 'Algo salió mal — inténtalo de nuevo en un momento.',
      send: 'Enviar comentario →',
      subject: 'Nuevo comentario en comparereligion.com',
      continueChapter: '▶ Continuar donde lo dejaste — Capítulo {n} →',
      share: {
        site: {
          title: 'Fe, Comparada',
          text: 'Diecisiete cosmovisiones. Una comparación honesta:',
          url: 'https://comparereligion.com/es/',
        },
        compare: {
          title: 'Fe, Comparada — Laboratorio',
          text: 'Compara las religiones del mundo lado a lado:',
          url: 'https://comparereligion.com/es/#/compare',
        },
      },
    },
  },
  hi: {
    brandTitle: 'विश्वास, तुलना',
    brandHtml: 'विश्वास<span>,</span> तुलना',
    nav: {
      home: 'होम',
      religions: 'सभी धर्म',
      compare: 'तुलना प्रयोगशाला',
      islam: 'ईसाई ↔ इस्लाम',
      evidence: 'साक्ष्य',
      questions: 'प्रश्न',
      objections: 'आपत्तियाँ',
      restoration: 'कौन-सा ईसाई धर्म?',
      atheism: 'नास्तिकता',
      sources: 'स्रोत',
      contact: 'संपर्क',
      philosophy: 'क्या मायने रखता है →',
      happiness: 'सुख →',
      stats: 'आगंतुक मानचित्र',
      menu: 'मेनू',
      openMenu: 'मेनू खोलें',
      closeMenu: 'मेनू बंद करें',
    },
    essayNav: { philosophy: [], happiness: [], stats: [] },
    footer: 'विश्वास, तुलना · सुसमाचार रक्षा स्रोतों से · मूल ग्रंथों से सदैव जाँच करें।',
    backToJourney: '← यात्रा पर वापस',
    backHome: '← होम',
    i18n: {
      sending: 'भेजा जा रहा है…',
      thanks: 'धन्यवाद — आपका संदेश भेज दिया गया है।',
      error: 'कुछ गलत हुआ — कृपया फिर प्रयास करें।',
      send: 'टिप्पणी भेजें →',
      subject: 'comparereligion.com पर नई टिप्पणी',
      continueChapter: '▶ जहाँ छोड़ा था वहीं से — अध्याय {n} →',
      share: {
        site: { title: 'विश्वास, तुलना', text: 'सत्रह विश्वदृष्टियाँ। एक ईमानदार तुलना।', url: 'https://comparereligion.com/hi/' },
        compare: { title: 'तुलना प्रयोगशाला', text: 'धर्मों को साथ-साथ देखें:', url: 'https://comparereligion.com/hi/#/compare' },
      },
    },
  },
  ml: {
    brandTitle: 'വിശ്വാസം, താരതമ്യം',
    brandHtml: 'വിശ്വാസം<span>,</span> താരതമ്യം',
    nav: {
      home: 'ഹോം', religions: 'മതങ്ങൾ', compare: 'താരതമ്യം', islam: 'ക്രൈസ്തവ ↔ ഇസ്ലാം',
      evidence: 'തെളിവ്', questions: 'ചോദ്യങ്ങൾ', objections: 'ആക്ഷേപങ്ങൾ', restoration: 'ഏത് ക്രൈസ്തവത?',
      atheism: 'നിരീശ്വരത', sources: 'സ്രോതസ്സുകൾ', contact: 'ബന്ധപ്പെടുക',
      philosophy: 'പ്രധാനം →', happiness: 'സന്തോഷം →', stats: 'സന്ദർശക ഭൂപടം',
      menu: 'മെനു', openMenu: 'മെനു തുറക്കുക', closeMenu: 'മെനു അടയ്ക്കുക',
    },
    essayNav: { philosophy: [], happiness: [], stats: [] },
    footer: 'വിശ്വാസം, താരതമ്യം · സുവിശേഷ അപോളജെറ്റിക്സ് · ഒറിജിനൽ ഗ്രന്ഥങ്ങൾ പരിശോധിക്കുക.',
    backToJourney: '← യാത്രയിലേക്ക്',
    backHome: '← ഹോം',
    i18n: {
      sending: 'അയയ്ക്കുന്നു…', thanks: 'നന്ദി — നിങ്ങളുടെ സന്ദേശം അയച്ചു.', error: 'എന്തോ കുഴപ്പം — വീണ്ടും ശ്രമിക്കുക.',
      send: 'അഭിപ്രായം അയയ്ക്കുക →', subject: 'comparereligion.com-ൽ പുതിയ അഭിപ്രായം',
      continueChapter: '▶ നിങ്ങൾ നിർത്തിയിടത്തു നിന്ന് — അധ്യായം {n} →',
      share: {
        site: { title: 'വിശ്വാസം, താരതമ്യം', text: 'പതിനേഴ് ലോകവീക്ഷണങ്ങൾ.', url: 'https://comparereligion.com/ml/' },
        compare: { title: 'താരതമ്യ ലാബ്', text: 'മതങ്ങൾ അരികിൽ വച്ച് താരതമ്യം ചെയ്യുക:', url: 'https://comparereligion.com/ml/#/compare' },
      },
    },
  },
  ta: {
    brandTitle: 'நம்பிக்கை, ஒப்பீடு',
    brandHtml: 'நம்பிக்கை<span>,</span> ஒப்பீடு',
    nav: {
      home: 'முகப்பு', religions: 'மதங்கள்', compare: 'ஒப்பீடு', islam: 'கிறிஸ்தவம் ↔ இஸ்லாம்',
      evidence: 'ஆதாரம்', questions: 'கேள்விகள்', objections: 'ஆட்சேபனைகள்', restoration: 'எந்த கிறிஸ்தவம்?',
      atheism: 'நாத்திகம்', sources: 'ஆதாரங்கள்', contact: 'தொடர்பு',
      philosophy: 'முக்கியம் →', happiness: 'மகிழ்ச்சி →', stats: 'பார்வையாளர் வரைபடம்',
      menu: 'பட்டி', openMenu: 'பட்டியைத் திற', closeMenu: 'பட்டியை மூடு',
    },
    essayNav: { philosophy: [], happiness: [], stats: [] },
    footer: 'நம்பிக்கை, ஒப்பீடு · சுவிசேஷ மன்னிப்புரை · மூல நூல்களை சரிபார்க்கவும்.',
    backToJourney: '← பயணத்திற்குத் திரும்பு',
    backHome: '← முகப்பு',
    i18n: {
      sending: 'அனுப்புகிறது…', thanks: 'நன்றி — உங்கள் கருத்து அனுப்பப்பட்டது.', error: 'பிழை — மீண்டும் முயலவும்.',
      send: 'கருத்து அனுப்பு →', subject: 'comparereligion.com இல் புதிய கருத்து',
      continueChapter: '▶ நிறுத்திய இடத்திலிருந்து — அத்தியாயம் {n} →',
      share: {
        site: { title: 'நம்பிக்கை, ஒப்பீடு', text: 'பதினேழு உலகப் பார்வைகள்.', url: 'https://comparereligion.com/ta/' },
        compare: { title: 'ஒப்பீட்டு ஆய்வகம்', text: 'மதங்களை அருகருகே ஒப்பிடுங்கள்:', url: 'https://comparereligion.com/ta/#/compare' },
      },
    },
  },
  zh: {
    brandTitle: '信仰对照',
    brandHtml: '信仰<span>，</span>对照',
    nav: {
      home: '首页', religions: '所有宗教', compare: '对照实验室', islam: '基督教 ↔ 伊斯兰教',
      evidence: '证据', questions: '问题', objections: '异议', restoration: '哪一种基督教？',
      atheism: '无神论', sources: '来源', contact: '联系',
      philosophy: '真正重要的 →', happiness: '幸福 →', stats: '访客地图',
      menu: '菜单', openMenu: '打开菜单', closeMenu: '关闭菜单',
    },
    essayNav: { philosophy: [], happiness: [], stats: [] },
    footer: '信仰对照 · 福音护教学来源 · 请始终对照原文核验。',
    backToJourney: '← 返回旅程',
    backHome: '← 首页',
    i18n: {
      sending: '发送中…', thanks: '谢谢 — 留言已送出。', error: '出错了 — 请稍后再试。',
      send: '发送留言 →', subject: 'comparereligion.com 新留言',
      continueChapter: '▶ 从上次离开的地方继续 — 第 {n} 章 →',
      share: {
        site: { title: '信仰对照', text: '十七种世界观。一次诚实对照。', url: 'https://comparereligion.com/zh/' },
        compare: { title: '对照实验室', text: '并排比较世界宗教：', url: 'https://comparereligion.com/zh/#/compare' },
      },
    },
  },
  ja: {
    brandTitle: '信仰、比較',
    brandHtml: '信仰<span>、</span>比較',
    nav: {
      home: 'ホーム', religions: 'すべての宗教', compare: '比較ラボ', islam: 'キリスト教 ↔ イスラム',
      evidence: '証拠', questions: '問い', objections: '反論', restoration: 'どのキリスト教？',
      atheism: '無神論', sources: '出典', contact: '連絡',
      philosophy: '大切なもの →', happiness: '幸福 →', stats: '訪問者マップ',
      menu: 'メニュー', openMenu: 'メニューを開く', closeMenu: 'メニューを閉じる',
    },
    essayNav: { philosophy: [], happiness: [], stats: [] },
    footer: '信仰、比較 · 福音弁証学の資料に基づく · 必ず原典で確かめてください。',
    backToJourney: '← 旅に戻る',
    backHome: '← ホーム',
    i18n: {
      sending: '送信中…', thanks: 'ありがとうございます — メッセージを送りました。', error: 'エラーです — もう一度お試しください。',
      send: 'コメントを送る →', subject: 'comparereligion.com への新しいコメント',
      continueChapter: '▶ 中断したところから — 第 {n} 章 →',
      share: {
        site: { title: '信仰、比較', text: '十七の世界観。誠実な比較を。', url: 'https://comparereligion.com/ja/' },
        compare: { title: '比較ラボ', text: '世界の宗教を並べて比較：', url: 'https://comparereligion.com/ja/#/compare' },
      },
    },
  },
};
